volumes:
  postgres_data_duolingo:
    driver: local
  redis_data_duolingo:
    driver: local

services:
  postgres_duolingo:
    container_name: postgres_duolingo
    image: postgres:15
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:      
      - postgres_data_duolingo:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin_duolingo:
    container_name: pgadmin_duolingo
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}
    depends_on:
      - postgres_duolingo
    restart: unless-stopped
  redis_duolingo:
    container_name: redis_duolingo
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data_duolingo:/data
    restart: unless-stopped
